### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by 814k31** [moreaup/cordova-plugin-aws-user-pool#3]
Trying out this package for the first time so if it's something obvious please let me know

I tried to match everything through the sample read me

This is my code:
```
var awsUserPluginInstance = new AwsUserPoolPlugin({
        "CognitoIdentityUserPoolId": 'ap-southeast-2_xxxxxxxxx',
        "CognitoIdentityUserPoolAppClientId": 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
        "CognitoIdentityUserPoolAppClientSecret": 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        "arnIdentityPoolId": 'ap-southeast-2:xxxxxxxxxxxx',
        "CognitoRegion": AwsUserPoolPlugin.AwsUserPoolPluginEnum.ApSoutheast2
    }, function (res) {
        console.log("connectionPluginInstance Init Ok", res);
    }, function (err) {
        console.error("connectionPluginInstance Init Fail", err);
    });
```

Which outputs:
` bundle.js:71639 connectionPluginInstance Init Fail Class not found `

I've tried two user pools as well

EDIT: This was only through android, I'm testing on ios now though it may appear I also have issue #2

**Comment by happygts** [comment]
On what platform are you testing the plugin ?

**Comment by 814k31** [comment]
@moreaup sorry, just edited my issue. I was trying it on android, although I'm also getting the linking error for ios (removing and readding didnt work)

**Comment by happygts** [comment]
I will check this out, thanks.
